# Generated by Django 5.2.7 on 2025-10-24 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai_images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('Black Tea', 'Black Tea'), ('Green Tea', 'Green Tea'), ('Herbal Tea', 'Herbal Tea'), ('Oolong Tea', 'Oolong Tea'), ('White Tea', 'White Tea'), ('Chai Latte', 'Chai Latte')], max_length=10)),
            ],
        ),
    ]
