# Generated by Django 5.2.7 on 2025-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default='Delicious chai variety.'),
        ),
    ]
